version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - EDITOR=vim
    ports:
      - "${RAILS_PORT:-3000}:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    tty: true
    volumes:
      - .:/api:cached
      - bundle:/usr/local/bundle

volumes:
  bundle:
  node_modules:
